version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: lifeuser
      POSTGRES_PASSWORD: lifepass
      POSTGRES_DB: lifedb
    ports:
      - "5555:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: lifeuser
      DB_PASSWORD: lifepass
      DB_NAME: lifedb
      DB_PORT: 5432
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
       NEXT_PUBLIC_API_URL: http://localhost:4000/recommendation
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend


volumes:
  db_data:
